name: rideapp
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_icons: ^1.1.0
  provider: ^4.1.2
  google_fonts: ^1.1.0
  google_maps_flutter: ^0.5.28
  geolocator: ^5.3.1
  google_sign_in: ^4.5.1
  firebase_messaging: ^6.0.15
  fluttertoast: ^4.0.1
  geocoder: ^0.2.1
  progress_dialog: ^1.2.3
  connectivity: ^0.4.8+6
  flutterpaytm: ^1.0.0
  flare_flutter: ^2.0.3
  cached_network_image: ^2.2.0+1
  sliding_up_panel: ^1.0.2
  permission: ^0.1.7
  android_intent: ^0.3.7+2
  http: ^0.12.1
  argon_buttons_flutter: 1.0.2
  url_launcher: 5.4.11
  flutter_spinkit: "^4.1.2"

  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_storage: ^3.1.5
  image_picker: ^0.6.6+4
  cupertino_icons: ^0.1.3
  google_map_location_picker: ^3.3.1
  google_map_polyline:
  device_preview: 0.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - asset/images/
    - asset/
