import 'package:flutter/material.dart';

class TermsAndConditions extends StatefulWidget {
  @override
  _TermsAndConditionsState createState() => _TermsAndConditionsState();
}

class _TermsAndConditionsState extends State<TermsAndConditions> {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SafeArea(
        child: Padding(
          padding: const EdgeInsets.all(8.0),
          child: Scrollbar(
            child: ListView(
              children: <Widget>[
                RichText(
                  text: TextSpan(
                    text: 'GENERAL TERMS & CONDITIONS:\n',
                    style: TextStyle(
                        fontSize: 15,
                        fontWeight: FontWeight.bold,
                        color: Colors.black),
                    children: <TextSpan>[
                      TextSpan(
                          text: "Welcome to Transport Desk.in\n \n",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                      TextSpan(
                          text:
                              "(Transportdesk.in) is governed by FRANKO INNOVTECH PVT.LTD. (Owner oftransportdesk.in) relation with you in relation of this website and mobile application.These terms and conditions (“User Terms”) apply to your visit to and use, of the Website or a mobile phone, the Service and the Application, as well as to all information, recommendations and or services provided to you on or through the Site, the Service and the Application. This document is an electronic record in terms of Information Technology Act, 2000 and rules thereunder as applicable and the provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. By clicking on the “I ACCEPT” button, you are consenting to be bound by these (“User Terms”).Please make sure that you read the General terms & Conditions before using this Website or Application. If you do not accept any of the (“User Terms”), then please do not use the Site or avail any of the services being provided therein. Your Agreement to these General Terms & Conditions shall operate as binding Agreement between you and transportdesk.in, in respect of the use and services of the site. Your acceptance of the (“User Terms”) shall be deemed to include your acceptance of the privacy policy available on the Website and the mobile Application. ALL THE USERS AVAILING OUR SERVICES WILL BE BOUND BY THE FOLLOWING RULES/USER TERMS AS FOLLOWS:",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                      TextSpan(
                          text: "\n \nDefinations ",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: "\nWe, transport desk ",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                      TextSpan(
                          text:
                              " shall refer to FRANKO INNOVTECH PVT.LTD (owner of transporterdesk.in), its authorised agents and the entities that carry or undertake to carry the consignment here under or perform any other services incidental thereto on its behalf.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\nYou, Your, consignor ",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall refer to the sender of the goods, consignor is the person who will avails our services for transportation of goods from one place to another.  ",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nReceiver or Consignee",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall refer to the recipient of the goods sent by consignor.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\nConsignment",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " means any package, parcel, goods that consigner sends to consignee.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nDelivery",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " means the tender of the consignment to the consignee or its intimation.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\nDangerous Goods",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " means goods classified as dangerous as per ICAO-T.I., IATA DGR, IMDG-Code, ADR or other national regulations for transport.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nProhibited Items",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " means any goods or materials, the Carriage of which is prohibited by any law, rule or regulation of India.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\nE-Wallet",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean a pre-paid instrument, which can be used to make payments.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nFare",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean such amount in Indian Rupees, which is reflected on the Application, as the fare payable for the specific Ride performed by a Driver. The Fare shall be exclusive of all applicable taxes on the Fare, if any. In relation to Tempo (a motor vehicle), the Fare shall be as prescribed by law and/or as stipulated by relevant authorities.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nApplication",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean the mobile application Transport Desk updated by Transport Desk from time to time.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nDriver",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean and include such individuals as may be evaluated, appointed and trained by an operator associated with us to provide the transportation services on its behalf and persons who are registered with transport desk  who have necessary commercial vehicle driving permits and other applicable transport vehicle permits and licenses to provide transportation services within and outside the city.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nConvenience Fee",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean the fee payable by the Customer to Transport Desk for the Service provided by Transport Desk using its technology door to door service, customer support and cashless payment options. Convenience Fee shall be chargeable on every booking made through the website or mobile application. The Convenience Fee shall be exclusive of all applicable taxes on the Convenience Fee, if any.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nCancellation Fee",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean the Fare and Convenience Fee payable towards cancellation of a Ride by a Customer mentioned in cancellation terms.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\nAdd-On Fee",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " shall mean any toll duty, inter-state taxes, etc. as may not be included in the Fare or not already paid as a part of the Total Ride Fee but payable to any third party / government authorities for undertaking the Ride under Applicable Law.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\n \nRegistration Terms:",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " You shall ensure that the Registration Data provided by you is accurate, complete, current, valid and true and is updated from time to time. We shall bear no liability for false, incomplete, old or incorrect Registration Data provided by you. We reserve the right to suspend or terminate Your Account with immediate effect and for an indefinite period, if we have a reason to believe that the Registration Data or any information provided by you is false in nature, security of your account has been compromised.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n \nService Terms:",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: " \n- Transport Desk reserves the right, at its sole discretion, to modify or replace, in part or full, any of these User Terms, or change, suspend, block, discontinue or restrict your use to all or any feature of the Service or Application at any time. \n -Transport Desk may give notice by means of a general notice on the Service or Application, or by electronic mail to your email address or a message on your registered mobile number, or by written communication sent by regular mail. \n -You shall not assign your rights under these User Terms without prior written approval of Transport Desk. Transport Desk can assign its rights under the User Terms to any affiliate. \n -Transport Desk reserves the right to immediately terminate the Service and the use of the Application in the event of non-compliance with any of the above requirements. Further, Transport Desk will store the information provided by you or record your calls for contacting you for all Service related matters. You shall promptly inform Transport Desk on any change in the information provided by you.\n -The customer shall pay the  Fare, parking charges, additional night surcharge (where applicable) and any fee or levy presently payable or hereinafter imposed by the law or required to be paid for availing of any category of commercial vehicle from transport desk.\n -The customer agrees and accepts that the use of the Services provided by the Company        is at the sole risk of the Customer, and further acknowledges that the Company disclaims all representations and warranties of any kind, whether express or implied.\n -Customer has no right over the driver of booked vehicle as follows: \n    1. To misuse the truck in any form. \n    2. To break any rules set by government and RTO of India. \m -The Customer/User shall indemnify Company from and against and in respect of any or all liabilities, losses, charges and expenses (including legal fees and costs on a full indemnity basis) claims, demands, actions and proceedings which Company may incur or sustain directly or indirectly from or by any reason of or in relation to the use or proposed use of the Services by the Customer and shall pay such sums when demanded by the Company. \n -GPS based information of the Users will be given to the telecommunication companies so that users could be facilitated with the tracking facility. \n -The company has full rights to cancel any booking of any user if they think it’s in the best interest of the company and can claim for the expenses for the booking from the User’s.\n -The User is liable to pay complete fare till the ride gets end by the driver.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -In case if toll tax is included in the trip toll for the current and return trip will be paid by the Customer/User over and above final fare.",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: "\n \n DISCLAIMER",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                           TextSpan(
                          text: "\nAll vehicles registered with the Company are continuously tracked using mobile technology for security reasons only. It is expressly made clear to you hereby that the Company does not own any truck nor does it directly or indirectly employ any drivers for the vehicle. Trucks and drivers are all supplied by third parties and the Company disclaims any and all liability in respect of the drivers and the Trucks alike.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n \nALL DISPUTES ARE SUBJECT TO GURGAON COURT JURISDICTION.",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                           TextSpan(
                          text: "\n \nCancellation Policy:",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20)),
                           TextSpan(
                          text: "\n\nLocal trips: \nFor Customer/User",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
                          TextSpan(
                          text: "\nAll cancellations made 5 mins after driver allocation will incur a cancellation fee of 30% of the estimated fare which is in INR on which the ride / truck has been booked. Cancelling three bookings in a day after driver allocation will temporarily suspend your account for 24 hours or until you clear your previous due charges . Figures are subject to change.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\nFor Drivers/Vendors",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15)),
                          TextSpan(
                          text: "\nAll cancellations made after accepting the ride and then denying/cancelling after the information of the truck has been shared to the customer/ person booking the truck will levy a charge of flat INR 50 / cancellation. If subsequently booking cancelled by the driver 3 times this will lead to temporary suspension of the vendor account. Figures are subject to change.",
                         style: TextStyle(fontWeight: FontWeight.normal)),
                         TextSpan(
                          text: "\n\nInsurance Information:",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20)),
                          TextSpan(
                          text: "\n -When you book a vehicle from transportdesk.in the goods are not insured. Our rates do not include any charges towards insurance. But the customer should take insurance for goods being shipped.\n -We do not provide any goods insurance as of till date.\n -In case of damage/theft/loss of goods if the customer has taken the insurance of goods from somewhere else, we can help in the survey process initiated by the Insurer of the customer. We can provide a Certificate of Facts, which is an important document for claiming the insurance.\n -In case of damage/theft/loss during the trip transportdesk.in is not liable either to customer or to the transporter.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\nGST TERMS:",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 20)),
                          TextSpan(
                          text: "\n -GST will be levied on the Invoice as applicable.\n -GST no. has to be provided by the vendors of the app otherwise it will be deposited by us as collected on their behalf. \n -Taxes on reverse charge mechanism, wherever applicable, shall have to be paid by the recipient of services.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\nDangerous Goods/Prohibited Items:",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                          TextSpan(
                          text: " \n\n-We do not carry, nor perform other services regarding, goods which are in our sole opinion Dangerous Goods including, but not limited to, those specified in the regulations, guidelines, technical instructions, codes applicable to us and our business or to the transport of, or the performance of other services regarding, Dangerous Goods.\n\n -We may at our discretion accept some Dangerous Goods for carriage, or for the performance of other services, in some locations if you have been accorded the status of an approved customer and this must be given by us in writing before your consignment can be accepted. Your Dangerous Goods will only be accepted if they comply with the applicable regulations and our requirements. Details of our requirements together with the procedure for applying for approved customer status are available from our nearest office and a dangerous goods surcharge will be invoiced to you upon acceptance of your consignment.\n\n-Prohibited Items: We do not accept consignments that contain prohibited items.\n\n -We accept consignments only upon your declaration of the type and value of the consignment (“said to contain” basis). We have no responsibility whatsoever as to the correctness of description, type or value thereof and you agree to indemnify us and hold us harmless from any claims that may be brought against us arising out of or relating to such declaration provided by you and any costs we will incur relating thereto.",
                          style: TextStyle(fontWeight: FontWeight.normal)),

                           TextSpan(
                          text: "\n\nCustomer’s obligations:",
                          style: TextStyle(fontWeight: FontWeight.bold, fontSize: 18)),
                          TextSpan(
                          text: "\n\n-Its sole responsibility of the customer to tell correct load weight and product to be loaded in the vehicle booked also provide truck driver with necessary road permits and invoices.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                           TextSpan(
                          text: "\n\n-It is sole responsibility of the customer to not load prohibited or dangerous goods as specified in above term as dangerous and prohibited goods also if the customer is entitled to send such goods along with these goods a declaration is also to be provided of those goods to the vehicle driver.",
                         style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-That all statements and information and documents provided by you relating to the Consignment will be true and correct and you acknowledge that in the event that you make untrue or fraudulent statement about the Consignment or any of its contents, you would risk a civil claim and/or criminal prosecution the penalties for which may include forfeiture and sale. You agree to indemnify us and hold us harmless from any claims that may be brought against us or our agents arising from the information provided by you.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-We will deliver the goods as per address mentioned by you in your in your goods drop location and will intimate you by the message and app notification no-response within 24 hours would be considered as an affirmative to the delivery.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-The party booking vehicle is liable to pay for the final fare we will not collect the fare from any other party.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-Customer/vehicle booking party agree to indemnify us and hold us harmless from any liabilities we may suffer or any costs, damages or expenses, including legal costs, we incur either to you or to anyone else arising out of you being in breach of any of these warranties, representations and guarantees, even if we inadvertently accept a consignment that contravenes any of your obligations. ",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-We are not liable if we do not fulfil any obligations towards you at all as a result of: Circumstances beyond our control such as (but not limited to):",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 1. Acts of god including earthquakes, cyclones, storms, flooding, fire, disease, fog, snow or frost or other natural calamities or disasters",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 2. Force majeure including (but not limited to) war, accidents, acts of public enemies, strikes, embargoes, perils of the air, local disputes or civil commotions.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 3. National or local disruptions in air or ground transportation networks and mechanical problems to modes of transport or machinery.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 4.Latent defects or inherent vice in the contents of the consignment.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 5. Criminal acts of third parties such as theft and arson.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-The customer agrees and acknowledges that the use of the Services offered by Company is at the sole risk of the customer and that Company disclaims all representations and warranties of any kind, whether express or implied as to condition, suitability, quality, merchantability and fitness for any purposes are excluded to the fullest extent permitted by law. Without prejudice to the above, the Company makes no representation or warranties with respect to:",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 1.The Services meeting the customer's requirements.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 2.The Services will be uninterrupted, timely, secure, or error-free.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 3.Any responsibility or liability for any loss or damage, howsoever caused or suffered by the Customer arising out of the use of truck service offered by Company or due to the failure of Company to provide Services to the Customer for any reason whatsoever including but not limited to the Customer's non-compliance with the Services' recorded voice instructions, malfunction, partial or total failure of any network terminal, data processing system, computer tele-transmission or telecommunications system or other circumstances whether or not beyond the control of Company or any person or any organization involved in the above mentioned systems.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 4.Any liability for any damages of any kind arising from the use of the Service offered by the Company, including, but not limited to direct, indirect, incidental, punitive, and consequential damages.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 5.Any additional or extra charges for far off locations & toll charges as well.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n 6.Any alternate arrangement(s) if the truck has not reached due to any reason.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n-Due to any consequences or penalties caused due to any untrue fact disclosed by you we are not liable to any such information provided by you and you will be the sole bearer of such penalties.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\nIntellectual Property Rights:",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: "\n-TransportDesk.in alone (and its licensors, where applicable) shall own all right, title and interest, including all related intellectual property rights, in and to",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n-Website, Application, product, Service and any suggestions, ideas, enhancement requests, feedback, recommendations or any other offering;",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n-Text, graphics, user interfaces, visual interfaces, photographs, trademarks, logos, sounds, music, artwork and computer code;",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n-Other information provided by you or any other party relating to the Site, Application or the Service. Third party trademarks may appear on this Site/ Application and all rights therein are reserved to the registered owners of those trademarks. For use of any third party's intellectual",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -Property, you need to get permission directly from the owner of the intellectual property for any use.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n - These User Terms do not constitute a sale and do not convey to you any rights of ownership in or related to the Site, the Application or the Service, or any intellectual property rights owned by Transportdesk.in. You shall be solely responsible for any violations of any laws and for any infringements of any intellectual property rights caused by use of the Services or the Website/ Application.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -You may use information on the Site purposely made available by Transportdesk.in for downloading from the Site, provided that You:",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -Do not remove any proprietary notice language in all copies of such documents and make no modifications to the information; ",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -Use such information only for Your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media;",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n -Do not make any additional representations or warranties relating to such information.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          TextSpan(
                          text: "\n\n Refund Policy:",
                          style: TextStyle(fontWeight: FontWeight.bold)),
                          TextSpan(
                          text: "\n -Once the payment has been made by the consignor to the transport desk at the time of pickup, No fare amount will be refunded if the consignor tries to cancel the trip after making payment. 100% fare amount will be forfeited by the transport desk.",
                          style: TextStyle(fontWeight: FontWeight.normal)),
                          

                           
                          

                           
                           
                          
                          
                           
                          
                          


                    ],
                  ),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
